name: LaTeX Action
on: 
  page_build: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy bibtex
        run: |
          cp assets/bibtex/myref.bib cv/own-bib.bib
      - uses: xu-cheng/latex-action@v3
        with:
          # The root LaTeX file to be compiled
          root_file: cv-llt.tex
          # The working directory for the LaTeX engine
          working_directory: cv # optional
          latexmk_use_xelatex: true

      - name: Upload to GitHub
        run: |
          mkdir cv_output
          cp cv/cv-llt.pdf cv_output/cv.pdf
          cd cv_output
          git init
          git config user.name github-actions
          git config user.email github-actions@github.com
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add *.pdf
          git commit -m "Updated CV"
          git push "${remote_repo}" HEAD:cv --force
          
